/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ["./src/**/*.{js,ts,jsx,tsx,mdx}"],
  darkMode: ["selector", '[data-theme="dark"]'],
  theme: {
    extend: {
      colors: {
        "surface-container-low": "#1c1b1d",
        surface: "#131315",
        outline: "#8d90a2",
        secondary: "#bec6e0",
        "tertiary-container": "#707171",
        "tertiary-fixed-dim": "#c6c6c7",
        "on-primary-fixed-variant": "#0039b5",
        "on-primary-fixed": "#001552",
        background: "#131315",
        "surface-container-highest": "#353437",
        "on-secondary": "#283044",
        "on-secondary-container": "#adb4ce",
        "on-background": "#e5e1e4",
        "surface-container-lowest": "#0e0e10",
        "primary-container": "#2e62ff",
        primary: "#b7c4ff",
        "outline-variant": "#434656",
        "surface-tint": "#b7c4ff",
        "inverse-surface": "#e5e1e4",
        "primary-fixed": "#dce1ff",
        "surface-dim": "#131315",
        "primary-fixed-dim": "#b7c4ff",
        "on-tertiary-fixed": "#1a1c1c",
        "surface-container-high": "#2a2a2c",
        "on-tertiary": "#2f3131",
        "on-secondary-fixed-variant": "#3f465c",
        tertiary: "#c6c6c7",
        "surface-container": "#201f22",
        "on-surface": "#e5e1e4",
        "on-secondary-fixed": "#131b2e",
        "secondary-fixed": "#dae2fd",
        "inverse-on-surface": "#313032",
        "on-tertiary-container": "#f6f7f7",
        "on-error-container": "#ffdad6",
        "on-error": "#690005",
        "on-primary": "#002682",
        "surface-variant": "#353437",
        error: "#ffb4ab",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#bec6e0",
        "on-primary-container": "#f7f6ff",
        "tertiary-fixed": "#e2e2e2",
        "surface-bright": "#39393b",
        "secondary-container": "#3f465c",
        "on-surface-variant": "#c3c5d8",
        "inverse-primary": "#024cec",
        "on-tertiary-fixed-variant": "#454747",
        brand: {
          blue: "#2E62FF",
          "blue-glow": "rgba(46, 98, 255, 0.15)",
        },
      },
      borderRadius: {
        DEFAULT: "0.125rem",
        lg: "0.25rem",
        xl: "0.5rem",
        full: "0.75rem",
      },
      spacing: {
        margin: "48px",
        unit: "4px",
        "container-max": "1440px",
        gutter: "24px",
      },
      fontFamily: {
        manrope: ["var(--font-manrope)", "Manrope", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        display: ["var(--font-manrope)", "Manrope", "sans-serif"],
        mono: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        "label-sm": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-md": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "headline-lg": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "body-md": ["var(--font-inter)", "Inter", "sans-serif"],
        "body-lg": ["var(--font-inter)", "Inter", "sans-serif"],
        "headline-xl": ["var(--font-manrope)", "Manrope", "sans-serif"],
        "label-mono": ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
      },
      fontSize: {
        "label-sm": ["12px", { lineHeight: "1.0", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "1.3", fontWeight: "500" }],
        "headline-lg": ["32px", { lineHeight: "1.2", letterSpacing: "-0.02em", fontWeight: "500" }],
        "body-md": ["15px", { lineHeight: "1.5", fontWeight: "400" }],
        "body-lg": ["18px", { lineHeight: "1.6", fontWeight: "400" }],
        "headline-xl": ["48px", { lineHeight: "1.1", letterSpacing: "-0.04em", fontWeight: "600" }],
        "label-mono": ["13px", { lineHeight: "1.0", letterSpacing: "0.05em", fontWeight: "500" }],
      },
      backgroundImage: {
        "technical-gradient":
          "radial-gradient(circle at top, rgba(46, 98, 255, 0.08) 0%, transparent 70%)",
        "card-gradient": "linear-gradient(to bottom right, rgba(255, 255, 255, 0.03), transparent)",
      },
      boxShadow: {
        "inner-glow": "inset 0 1px 0 0 rgba(255, 255, 255, 0.05)",
        "soft-blue": "0 0 40px -10px rgba(46, 98, 255, 0.2)",
      },
      borderColor: {
        "white-fade": "rgba(255, 255, 255, 0.05)",
        "white-border": "rgba(255, 255, 255, 0.1)",
      },
    },
  },
  plugins: [],
};
